# Generated by Django 3.2.18 on 2023-04-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('number_guests', models.IntegerField()),
                ('booking_comments', models.TextField(blank=True, max_length=500)),
                ('high_chair', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Unapproved'), (1, 'Approved')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
