# Generated by Django 3.2.18 on 2023-05-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_userprofile_createprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
